config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, only: [:show, :allpost]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'hello#index'

  get 'hello/link' => 'hello#link'

  get 'users/sign_in' => 'users#settions'
  
  get 'users/:id/all_posts' => 'users#all_posts'

  get 'users/:id/all_likes' => 'users#all_likes'

  get 'users/:id/followings' => 'users#followings'

  get 'users/:id/followers' => 'users#followers'

  get 'posts' => 'posts#index'

  get 'posts/new' => 'posts#new'

  post 'posts' => 'posts#create'

  get 'posts/:id' => 'posts#show',as: 'post'
    
  patch 'posts/:id' => 'posts#update'

  delete 'posts/:id' => 'posts#destroy'
  
  get 'posts/:id/edit' => 'posts#edit', as:'edit_post'

  root 'hello#index'

  resources :users, only: [:index, :show] do
    collection do
      get :likes
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
    acts_as_taggable
    belongs_to :user
    default_scope -> { order(created_at: :desc) } # 投稿が降順に表示
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: { maximum: 20 }
    validates :product, presence: true, length: { maximum: 20 }
    validates :maker, presence: true, length: { maximum: 20 }
    validates :rate, presence: true
    validates :alcohol, presence: true
    validates :body, presence: true, length: { maximum: 140 }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
      #検索機能
      if params[:search] != nil && params[:search] != ''
        @posts = Post.where("product LIKE ? ",'%' + params[:search] + '%') .or Post.where("maker LIKE ? ",'%' + params[:search] + '%') .or Post.where("body LIKE ? ",'%' + params[:search] + '%')
      elsif params[:tag_name]
        @posts = Post.tagged_with("#{params[:tag_name]}")
      else
        @posts = Post.all
      end
      #ページネーション 
      @pagination = Post.page(params[:page]).per(10)
    end

    def new
      @post = Post.new
    end

    # 投稿
    def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save
        redirect_to :action => "index"
      else
        render action: :new
      end
    end

    #update

    def show
      @post = Post.find(params[:id])
      @like = Like.new
      @comments = @post.comments
      @comment = @post.comments.build
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to :action => "show", :id => @post.id
      else
        render action: :edit
      end
    end


    def destroy
      Post.find(params[:id]).destroy
      redirect_to action: :index
    end

    #認証　投稿一覧と詳細は認証を外す
    before_action :authenticate_user!, except: [:index, :show]
    
    private

  def post_params
    params.require(:post).permit(:title,:body,:product,:maker,:rate,:alcohol,:image, :tag_list)
  end






end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="posts-container">
  <div class="form-container">
    <p class="title">編集</p>
    <%= form_for @post do |f| %>
      <!-- エラーメッセージ -->
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.text_field :title,size: 80, :class => 'title-form', :placeholder => 'タイトル' %><br>
      <%= f.text_field :product,size: 80, :placeholder => '商品名' %>
      <%= f.text_field :maker,size: 80, :placeholder => 'メーカー' %>
      <p>評価（最高: ☆×5 最低: ☆×1)</p>
      <%= f.select :rate, [["☆×5", "5"], ["☆×4", "4"], ["☆×3", "3"], ["☆×2", "2"], ["☆×1", "1"]], include_blank: "選択して下さい" %>
      <p>アルコール度数</p>
      <%= f.select :alcohol, [["超ストロング（10%以上)", "超ストロング（10%以上)"], ["ストロング(7%〜9%)", "ストロング(7%〜9%)"], ["中(4%〜6%)", "中(4%〜6%)"], ["弱(3%以下)", "弱(3%以下)"], ["ノンアルコール", "ノンアルコール"]], include_blank: "選択して下さい" %>
      <p>本文</p>
      <%= f.text_area :body,size: 140, :class => 'body-form' %>
      <p>写真</p>
      <%= f.file_field :image %>
      <%= f.text_field :tag_list, value: @post.tag_list.join(','), size: 80 , :placeholder => 'タグ' %>
      <%= f.submit "編集する", class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="posts-container">
  <p class="page-title">Gokugoku Memo</h1>

  <div class="btn-container">
    <div class="btn">
      <%= link_to "投稿", posts_new_path %>
    </div>
    <input type="button" id="btn" value='検索'>

  </div>

  <!-- モーダル -->
  <%= render 'layouts/modal_search', model: "posts" %>

  <!--投稿表示-->
  <div class="post-container">
    <% @posts.each do |t| %>
    <div class="post-wrapper">
      <div class="post">
        <img src=<%= t.image_url %> class="post-image">
        <%= link_to "", post_path(t.id) %>
        <div class="post-option">
          <h4>♡ <%= t.liked_users.count %></h4>
        </div>
      </div>
      <div class="post-info">
        <div class="post-user">
          <% if t.user.image? %>
          <img src=<%= t.user.image %> class="mini-icon">
          <% else %>
          <img src="/assets/noicon.jpg" class="mini-icon">
          <% end %>
          <p><%= t.user.name %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%= paginate @pagination %>

</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'posts', :media => "all" %>

<div class="posts-container">
  <div class="form-container">
    <p class="title">新規投稿</p>
    <%= form_for @post do |f| %>
    <!-- エラーメッセージ -->
    <%= render 'layouts/error_messages', model: f.object %>
    <%= f.text_field :title,size: 80, :class => 'title-form', :placeholder => 'タイトル' %>
    <%= f.text_field :product,size: 80, :placeholder => '商品名' %>
    <%= f.text_field :maker,size: 80 , :placeholder => 'メーカー' %>
    <p>評価（最高: ☆×5 最低: ☆×1)</p>
    <%= f.select :rate, [["☆×5", "5"], ["☆×4", "4"], ["☆×3", "3"], ["☆×2", "2"], ["☆×1", "1"]], include_blank: "選択して下さい" %>
    <p>アルコール度数</p>
    <%= f.select :alcohol, [["超ストロング（10%以上)", "超ストロング（10%以上)"], ["ストロング(7%〜9%)", "ストロング(7%〜9%)"], ["中(4%〜6%)", "中(4%〜6%)"], ["弱(3%以下)", "弱(3%以下)"], ["ノンアルコール", "ノンアルコール"]], include_blank: "選択して下さい" %>
    <p>本文</p>
    <%= f.text_area :body,size: 140, :class => 'body-form' %>
    <p>写真</p>
    <%= f.file_field :image %>
    <%= f.text_field :tag_list, value: @post.tag_list.join(','), size: 80 , :placeholder => 'タグ' %>
    <p class="tag-discription">複数指定したい場合は半角カンマで区切ってください。</p>
    <p class="tag-discription">例: ノンアルコール,飲みやすい,酔いにくい,ストロング</p>
    <%= f.submit "送信", class: "submit-btn"%>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="posts-container">
  <p class="page-title"><%= @post.title %></p>
  <div class="p-wrapper">
    <div class="left-side">
      <p><%= @post.product %></p>
      <p><%= @post.maker %></p>
      <p>度数: <%= @post.alcohol%></p>
      <p> 
      <% if @post.rate == 1 %>
        <img src ="/assets/star-on">
        <img src ="/assets/star-off">
        <img src ="/assets/star-off">
        <img src ="/assets/star-off">
        <img src ="/assets/star-off">
      <% elsif @post.rate == 2%>
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-off">
        <img src ="/assets/star-off">
        <img src ="/assets/star-off">
      <% elsif @post.rate == 3%>
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-off">
        <img src ="/assets/star-off">
      <% elsif @post.rate == 4%>
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-off">
      <% elsif @post.rate == 5%>
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
        <img src ="/assets/star-on">
      <% end %>
      </p>
      <p><%= safe_join(@post.body.split("\n"),tag(:br)) %></p>
    </div>
    <div class="right-side">
      <div class="img-wrapper">
        <div class="img-tape"></div>

        <% if @post.image? %>
          <%= image_tag @post.image_url %>
        <% else %>
          <img src="/assets/noimage.png">
        <% end %>
      </div>
    </div>

    <div class="bottom-side">

      <p><%= @post.created_at.to_fs(:datetime_jp) %></p>

      <!-- タグ機能 -->
      <div class="tags">
        <% @post.tag_list.each do |tag| %>
          <%= link_to "#" + tag, posts_path(tag_name: tag), class: "tag" %>
        <% end%>
      </div>

      <!-- user -->
      <div class="user-wrapper">
        <div class="user-info">
          <% if @post.user.image? %>
            <img src=<%= @post.user.image %>>
          <% else %>
            <img src="/assets/noicon.jpg">
          <% end %>
          <a href="/users/<%= @post.user.id %>"><%= @post.user.name %></a>
        </div>
      </div>

      <!-- sns-share -->
      <div class="share-wrapper">
        <div class="sns-share">
        <a href="http://twitter.com/share?url=gokugoku.herokuapp.com/posts/<%= @post.id %>&hashtags=<%= @post.title %>" class="share twitter">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.facebook.com/sharer/sharer.php?u=gokugoku.herokuapp.com/posts/<%= @post.id %>" class="share facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
        </div>
      </div>

      <p class="like"><i class="fas fa-heart"></i> <%= @post.likes.count %></p>
      <!-- 投稿者なら編集・削除、それ以外のユーザーならいいねボタンを表示 -->
      <% if user_signed_in? && current_user.id == @post.user_id %> 
        <div class="btn"> 
          <%= link_to "編集", edit_post_path(@post.id) %>
        </div>
        <div class="btn danger-btn">
          <%= link_to "削除", post_path(@post.id), data: { confirm: "投稿を削除しますか？" }, method: :delete %>
        </div>
      <% elsif user_signed_in? && current_user.id != @post.user_id %>
        <% if current_user.already_liked?(@post) %>
          <%= button_to '取り消す', post_like_path(@post), method: :delete, class: "good-btn"%>
        <% else %>
          <%= button_to 'いいね！', post_likes_path(@post), class: "good-btn"%>
        <% end %>
      <% end %>




    </div>

  

    <div class="comment-wrapper">
      <p class="comment-title">Comment</p>
      
      <% @comments.each.with_index(1) do |c, i| %>
        <!-- 最新コメントとして空のコメントが表示されるバグがあったので、最新コメントが表示されない処理-->
        <% if i != @comments.size %> 
          <div class="comment">
            [<%= i %>]
            <a href="/users/<%= c.user.id %>"><%= c.user.name %></a>
            <% if user_signed_in? && current_user.id == c.user.id %>
              <%= link_to '削除', post_comment_path(@post, c), data: { confirm: "コメントを削除しますか？" }, method: :delete %>
            <% end %>
            <br>
            <%= safe_join(c.comment.split("\n"),tag(:br)) unless c.comment.blank? %>
          </div>
          <br>
          
        <% end %>
      <% end %>

      <% if @comments.count == 0%>
        <p>コメントはありません。</p>
        <br>
      <% end %>
      
      <% if user_signed_in? %>
        <%= form_with(model: [@post, @comment], local: true) do |f| %>
          <%= f.text_area :comment, :placeholder => 'コメントを入力' %>
          <%= button_tag type: "submit", class: "submit-btn" do%>
            <p>投稿</p>
          <% end %>
        <% end %>
        <% else %>
        <p>コメントを投稿するにはログインしてください。</p>
      <% end %>
    </div>
    <br>
  </div>
</div>