config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, only: [:show, :allpost]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'hello#index'

  get 'hello/link' => 'hello#link'

  get 'users/sign_in' => 'users#settions'
  
  get 'users/:id/all_posts' => 'users#all_posts'

  get 'users/:id/all_likes' => 'users#all_likes'

  get 'users/:id/followings' => 'users#followings'

  get 'users/:id/followers' => 'users#followers'

  get 'posts' => 'posts#index'

  get 'posts/new' => 'posts#new'

  post 'posts' => 'posts#create'

  get 'posts/:id' => 'posts#show',as: 'post'
    
  patch 'posts/:id' => 'posts#update'

  delete 'posts/:id' => 'posts#destroy'
  
  get 'posts/:id/edit' => 'posts#edit', as:'edit_post'

  root 'hello#index'

  resources :users, only: [:index, :show] do
    collection do
      get :likes
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <p>エラー</p>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_modal_search.html.erb
<div id="modal" class="modal">
  <div class="modal-content">
    <div class="modal-body">
      <p class="title">Search</p>
      <!-- renderで受け取った変数をmodelに代入 -->
      <%= form_tag( model, method: :get) do %>
      <div class="search-form">
        <%= text_field_tag :search %>
        <input type="submit" value="&#xf002;" class="fas search-btn">
      </div>

      <% if model == "posts" %>
      <p>おすすめタグで検索</p>
      <div class="tag-wrapper">
        <%= link_to "#ストロング", posts_path(tag_name: "ストロング"), class: "tag" %>
        <%= link_to "#飲みやすい", posts_path(tag_name: "飲みやすい"), class: "tag" %>
        <%= link_to "#ノンアルコール", posts_path(tag_name: "ノンアルコール"), class: "tag" %>
        <%= link_to "#ビール", posts_path(tag_name: "ビール"), class: "tag" %>
      </div>
      <% end %>
      <% end %>


      <button id="closeBtn">
        <i class="fas fa-times"></i> CLOSE
      </button>
    </div>
  </div>
</div>

<%= javascript_pack_tag "modal/application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>gokugoku</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <h1><%= link_to "gokugoku", root_path %></h1>
    <div class="header-list">
      <ul>
        <li><%= link_to "Memo",  posts_path %></li>
        <% if user_signed_in? %>
        <li>
          <a href="/users/<%= current_user.id %>">
            <% if current_user.image? %>
            <img src=<%= current_user.image %>>
            <% else %>
            <img src="/assets/noicon.jpg">
            <% end %>
            <%= current_user.name %>
          </a>
        </li>
        <% else %>
        <li><%= link_to "Sign in", users_sign_in_path %></li>
        <% end %>
      </ul>
    </div>

    <!-- ハンバーガーメニュー　PCでは非表示-->
    <div id="nav-drawer">
      <input id="nav-input" type="checkbox" class="nav-unshown">
      <label id="nav-open" for="nav-input"><span></span></label>
      <label class="nav-unshown" id="nav-close" for="nav-input"></label>
      <div id="nav-content">

        <!-- PC用メニュー　スマホでは非表示-->
        <ul>
          <% if user_signed_in? %>
          <li><%= link_to "My page", user_path(current_user.id) %></li>
          <% else %>
          <li><%= link_to "Sign in", users_sign_in_path %></li>
          <% end %>
          <li><%= link_to "Memo",  posts_path %></li>
          <li><%= link_to 'Top', root_path %></li>
        </ul>
      </div>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>


    <div class="left-side">
      <p>gokugoku</p>
    </div>

    <div class="middle-side">
      <p>製作者ホームページ（準備中）</p>
      <p>お問い合わせ（準備中）</p>
    </div>

    <div class="right-side">
      <!-- Twitter -->
      <p>Share:</p>
      <a href="http://twitter.com/share?url=gokugoku.herokuapp.com&hashtags=gokugokuで宅飲みライフを共有しよう" class="sns twitter-share">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://www.facebook.com/sharer/sharer.php?u=gokugoku.herokuapp.com" class="sns facebook-share">
        <i class="fab fa-facebook-f"></i>
      </a>
    </div>

    <div class="bottom-side">
      <p>未成年者の飲酒は法律で固く禁じられています。</p>
      <p>@All right reserved gokugoku 2020</p>
    </div>


  </footer>
</body>

</html>